name: Deploy API to Render (Webhook)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK not set. Skipping."
            exit 0
          fi
          curl -s -X POST "$RENDER_DEPLOY_HOOK"
